### PR TITLE
prevent regex mismatch from causing uncaught exception

### PR DESCRIPTION
**Pull request by AccaliaDeElementia**
resolves secondary error in https://github.com/scottgonzalez/node-git-tools/issues/9

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This is masking a real problem. I need the steps to reproduce the problem.

**Comment by yamikuronue** [comment]
Looks like you're splitting on the first space? Why use a regex?

**Comment by scottgonzalez** [comment]
That regex expresses much more semantics than just arbitrarily splitting on the first space. As I've said above, this is not a solution, because it does not show what the underlying problem is.

**Comment by yamikuronue** [comment]
oh, I agree, I just wanted to get a better sense of what's going on, I might submit my own PR later.

**Comment by scottgonzalez** [comment]
I dug into the problem by running your script. The problem is that you're asking for a list of authors from the boundary commit. There are no authors because you're looking before history exists. I'm going to make the `.authors()` method handle the case of no history, but your script is still going to blow up because you're doing things you shouldn't be doing. When you run a blame and get back a boundary commit, you shouldn't be trying to get any information from the boundary commit. You have to remove the boundary marker to get the initial commit SHA.

**Comment by scottgonzalez** [comment]
You can upgrade to v0.2.1 and the error should move further into your script (outside of git-tools).

**Pull request closed without merging**
